import type { Metadata } from "next";
import "./globals.css";
import DashboardWrap from "./dashboardWrap";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      > <DashboardWrap> 
        {children}
        </DashboardWrap>
      </body>
    </html>
  );
}
