import type { Metadata } from "next";
import "./globals.css";
import DashboardWrap from "./dashboardWrap";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DashboardWrap>
            {children}
          </DashboardWrap>
        </ThemeProvider>
      </body>
    </html>
  );
}
